routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/sign-In', function () {
	return view('pages.signIn');
});

Route::get('/signup', function () {
	return view('pages.signup');
});

Route::get('/dashboard', function () {
	return view('pages.dashboard');
})->name('dashboard')->middleware('auth')->middleware('verified');

Route::get('/tasks', function () {
	return view('pages.tasks');
});

Route::get('/appointments', function () {
	return view('pages.appointments');
});

Route::get('/appointmentNotes', function () {
	return view('pages.appointmentNotes');
});

Route::get('/myProfile', function () {
	return view('pages.myProfile');
});

Route::get('/uploads', function () {
	return view('pages.uploads');
});

Route::get('/packages', function () {
	return view('pages.packages');
});

Route::get('/paymentSuccessful', function () {
	return view('pages.paymentSuccessful');
});

Route::get('/sessionVideo', function () {
	return view('pages.recordedSessionVideo');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::post('change-password', 'ChangePasswordController@save')->name('change-password');

Route::resource('/users', 'UserController');
// Route::resource('/tasks', 'TaskController');
// Route::resource('/packages', 'PackageController');
// Route::resource('/appointments', 'AppointmentsController');

// Controllers Within The "App\Http\Controllers\Admin" Namespace
Route::namespace('Admin')
	->prefix('admin')
	->name('admin.')
	->group(function () {
		Route::get('/', function () {
	        return view('admin.login');
	    })
	    ->name('login')
	    ->middleware('guest');

		Route::get('/dashboard', function () {
	        return view('admin.dashboard');
	    })->name('dashboard');
	    
	    Route::get('change-password', 'ChangePasswordController@index')
			->name('password.change');
		Route::post('change-password', 'ChangePasswordController@store')
			->name('password.update');
	    
		//Resource routes
		Route::resource('/users', 'UserController');
		Route::resource('/packages', 'PackageController');
		Route::resource('/tasks', 'TaskController');
		Route::resource('/quote-videos', 'QuoteVideoController');
		Route::resource('/user-profiles', 'UserProfileController');
		Route::resource('/user-tasks', 'UserTaskController');
		Route::resource('/appointments', 'AppointmentController');
		Route::resource('/user-forms', 'UsersFromController');
	});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Kyslik\ColumnSortable\Sortable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Task extends Model
{
    use Notifiable, Sortable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'user_id'
    ];

    /**
     * The accessors attributes that should be available in json.
     *
     * @var array
     */
    protected $appends = ['hash_id'];

    public function getHashIdAttribute() {
        $hashids = new \Hashids\Hashids(config('app.key'));
        return $hashids->encode($this->id);
    }

    public function user() {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use \App\Task;
use Illuminate\Support\Facades\Auth;

class TaskController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $tasks = Task::withTrashed()
            ->sortable()
            ->paginate(15);
        } catch (\Kyslik\ColumnSortable\Exceptions\ColumnSortableException $e) {
        }
        
        $users = \App\User::where(['role_id' => config('custom.roles.student')])->get();
        return view('admin.task.index', [
            'tasks' => $tasks,
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //creating package
        $data=$request->input();
        $data['user_id'] = Auth::user()->id;
        $package = Task::create($data);
        return redirect(route('admin.tasks.index'))
            ->with('success', 'Task has been created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        $data=$request->input();
        $task->fill($data);
        $task->save();
        return redirect()->route('admin.tasks.index')
            ->with('success', "Task has been updated successfully.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::withTrashed()->find($id);
        $message='deleted';
        if ($task->trashed()) {
            $task->restore();
            $message='restored';
        } else {
            $task->delete();
        }

        return back()
            ->with('success', "Task has been $message successfully.");
    }
}

resources/views/modals/admin/task/add.blade.php
<!-- Modal -->
<div class="modal fade" id="addTaskModal" tabindex="-1" role="dialog" aria-labelledby="addTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add Task</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{ route('admin.tasks.store') }}" id="TaskForm">
                    @csrf
                    <div class="form-group">
                        <label for="Name">{{ __('Task Name') }}</label>
                        <input name="name" class="form-control" id="Name" required>
                        @error('name')
                            <label class="">{{ $message }}</label>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="Description">{{ __('Description') }}</label>
                        <textarea name="description" class="form-control" id="Description" required></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" form="TaskForm" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

resources/views/modals/admin/task/assign.blade.php
<!-- Modal -->
<div class="modal fade" id="assignTaskModal" tabindex="-1" role="dialog" aria-labelledby="editTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Assign Task</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="{{route('admin.user-tasks.store')}}" id="AssignTaskForm">
                    @csrf
                    <div class="form-group">
                        <label for="UserID">{{ __('Select Client') }}</label>
                        <select name="user_id" class="form-control" id="UserID" required>
                            @foreach($users as $user)
                                <option value="{{$user->id}}">
                                    {{$user->full_name}}
                                </option>
                            @endforeach
                        </select>
                        @error('name')
                            <label class="">{{ $message }}</label>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="TaskId">{{ __('Select Task') }}</label>
                        <select name="task_id" class="form-control" id="TaskId" required>
                            @foreach($tasks as $task)
                                <option value="{{$task->id}}">
                                    {{$task->name}}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="TaskId">{{ __('Task Date') }}</label>
                        <input name="task_date" class="form-control" id="TaskDate" required>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" form="AssignTaskForm" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

resources/views/modals/admin/task/edit.blade.php
<!-- Modal -->
<div class="modal fade" id="editTaskModal" tabindex="-1" role="dialog" aria-labelledby="editTaskModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Task</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="" id="EditTaskForm">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="Name">{{ __('Task Name') }}</label>
                        <input name="name" class="form-control" id="Name" required>
                        @error('name')
                            <label class="">{{ $message }}</label>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="Description">{{ __('Description') }}</label>
                        <textarea name="description" class="form-control" id="Description" required></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" form="EditTaskForm" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>