routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/sign-In', function () {
	return view('pages.signIn');
});

Route::get('/signup', function () {
	return view('pages.signup');
});

Route::get('/dashboard', function () {
	return view('pages.dashboard');
})->name('dashboard')->middleware('auth')->middleware('verified');

Route::get('/tasks', function () {
	return view('pages.tasks');
});

Route::get('/appointments', function () {
	return view('pages.appointments');
});

Route::get('/appointmentNotes', function () {
	return view('pages.appointmentNotes');
});

Route::get('/myProfile', function () {
	return view('pages.myProfile');
});

Route::get('/uploads', function () {
	return view('pages.uploads');
});

Route::get('/packages', function () {
	return view('pages.packages');
});

Route::get('/paymentSuccessful', function () {
	return view('pages.paymentSuccessful');
});

Route::get('/sessionVideo', function () {
	return view('pages.recordedSessionVideo');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::post('change-password', 'ChangePasswordController@save')->name('change-password');

Route::resource('/users', 'UserController');
// Route::resource('/tasks', 'TaskController');
// Route::resource('/packages', 'PackageController');
// Route::resource('/appointments', 'AppointmentsController');

// Controllers Within The "App\Http\Controllers\Admin" Namespace
Route::namespace('Admin')
	->prefix('admin')
	->name('admin.')
	->group(function () {
		Route::get('/', function () {
	        return view('admin.login');
	    })
	    ->name('login')
	    ->middleware('guest');

		Route::get('/dashboard', function () {
	        return view('admin.dashboard');
	    })->name('dashboard');
	    
	    Route::get('change-password', 'ChangePasswordController@index')
			->name('password.change');
		Route::post('change-password', 'ChangePasswordController@store')
			->name('password.update');
	    
		//Resource routes
		Route::resource('/users', 'UserController');
		Route::resource('/packages', 'PackageController');
		Route::resource('/tasks', 'TaskController');
		Route::resource('/quote-videos', 'QuoteVideoController');
		Route::resource('/user-profiles', 'UserProfileController');
		Route::resource('/user-tasks', 'UserTaskController');
		Route::resource('/appointments', 'AppointmentController');
		Route::resource('/user-forms', 'UsersFromController');
	});

resources/views/admin/change_password.blade.php
@extends('layouts.admin')
@section('content')
	<section>
	    <div class="container-fluid">
	      	<!-- Page Header-->
	      	<header> 
	      		<div class="row">
	      			<div class="col-6">
	        			<h2>Change Password</h2>
	      			</div>
	      		</div>
            	<x-alert/>		
	      	</header>
	      	<div class="row">
	        	<div class="col-md-7 mx-auto">
	          		<div class="card">
		                <div class="card-body">
		                  	<form method="POST" action="{{ route('admin.password.update') }}" id="ChangePasswordForm">
	                            @csrf
	                            <div class="form-group">
	                                <label for="Password">{{ __('Current Password') }}</label>
	                                <input type="password" name="current_password" class="form-control" id="Password" required>
	                                @error('current_password')
	                                    <label class="">{{ $message }}</label>
	                                @enderror
	                            </div>
	                            <div class="form-group">
	                                <label for="NewPassword">{{ __('New Password') }}</label>
	                                <input type="password" name="new_password" class="form-control" id="NewPassword" required>
	                            </div>
	                            <div class="form-group">
	                                <label for="ConfirmPassword">{{ __('Confirm New Password') }}</label>
	                                <input type="password" name="new_confirm_password" class="form-control" id="ConfirmPassword" required>
	                            </div>
	                            <div class="form-group text-right">
	                            	<a href="{{route('admin.packages.index')}}" class="btn btn-default">Cancel</a>
	                            	<button type="submit" class="btn btn-success">Submit</button>
	                            </div>
	                        </form>
		                </div>
	              	</div>
	            </div>
	      	</div>
	    </div>
	</section>
@endsection
@push('css')
	<link rel="stylesheet" href="{{ asset('css/common/jquery-ui.css') }}"></link>
@endpush
@push('scripts')
    <script type="text/javascript" src="{{asset('js/common/jquery-ui.js')}}"></script>
    <script src="{{ asset('js/common/jquery-validation/jquery.validate.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/admin/change-password.js') }}"></script>
@endpush

resources/views/admin/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Admin Login</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="all,follow">
        <link href="{{ asset('css/common.css') }}" rel="stylesheet">   
    </head>
    <body>
        <section>
            <div class="row" style="height:95vh;">
                <div class="col-sm-6 col-md-4 mx-auto my-auto" style="background-color:#fff ">
                    <div class="login-sec">
                        <h2 class="text-center">{{ __('Admin Login') }}</h2>
                        <form method="POST" action="{{ route('login') }}">
                            @csrf
                            <div class="form-group">
                                <label for="EmailInput" class="text-uppercase">{{ __('Email') }}</label>

                                <input type="email" name="email" class="form-control" placeholder="Email Address" id="EmailInput" value="{{ old('email') }}" required autocomplete="email" autofocus>
                                
                                @error('email')
                                    <label class="">{{ $message }}</label>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="PasswordInput" class="text-uppercase">Password</label>                                
                                <input id="PasswordInput" type="password" class="form-control @error('password') is-invalid @enderror" name="password" required autocomplete="current-password">
                                @error('password')
                                    <label class="">{{ $message }}</label>
                                @enderror
                            </div>          
                            <div class="form-check">
                                <label class="form-check-label">
                                    <input class="form-check-input" type="checkbox" name="remember" id="remember" {{ old('remember') ? 'checked' : '' }}>
                                    <small>Remember Me</small>
                                </label>
                                <button type="submit" class="btn btn-login float-right">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
        </section>
        <!-- JavaScript files-->
        <script src="{{ asset('js/common.js') }}"></script>
        <style type="text/css">
            body {
                background: #DE6262;  /* fallback for old browsers */
                /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera */
            }
            .login-sec{padding: 50px 30px; position:relative;}
            .login-sec .copy-text{position:absolute; width:80%; bottom:20px; font-size:13px; text-align:center;}
            .login-sec .copy-text i{color:#FEB58A;}
            .login-sec .copy-text a{color:#E36262;}
            .login-sec h2{margin-bottom:30px; font-weight:800; font-size:30px; color: #DE6262;}
            .login-sec h2:after{content:" "; width:100px; height:5px; background:#FEB58A; display:block; margin-top:20px; border-radius:3px; margin-left:auto;margin-right:auto}
            .btn-login{background: #DE6262; color:#fff; font-weight:600;}
        </style>
    </body>
</html>