routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/sign-In', function () {
	return view('pages.signIn');
});

Route::get('/signup', function () {
	return view('pages.signup');
});

Route::get('/dashboard', function () {
	return view('pages.dashboard');
})->name('dashboard')->middleware('auth')->middleware('verified');

Route::get('/tasks', function () {
	return view('pages.tasks');
});

Route::get('/appointments', function () {
	return view('pages.appointments');
});

Route::get('/appointmentNotes', function () {
	return view('pages.appointmentNotes');
});

Route::get('/myProfile', function () {
	return view('pages.myProfile');
});

Route::get('/uploads', function () {
	return view('pages.uploads');
});

Route::get('/packages', function () {
	return view('pages.packages');
});

Route::get('/paymentSuccessful', function () {
	return view('pages.paymentSuccessful');
});

Route::get('/sessionVideo', function () {
	return view('pages.recordedSessionVideo');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::post('change-password', 'ChangePasswordController@save')->name('change-password');

Route::resource('/users', 'UserController');
// Route::resource('/tasks', 'TaskController');
// Route::resource('/packages', 'PackageController');
// Route::resource('/appointments', 'AppointmentsController');

// Controllers Within The "App\Http\Controllers\Admin" Namespace
Route::namespace('Admin')
	->prefix('admin')
	->name('admin.')
	->group(function () {
		Route::get('/', function () {
	        return view('admin.login');
	    })
	    ->name('login')
	    ->middleware('guest');

		Route::get('/dashboard', function () {
	        return view('admin.dashboard');
	    })->name('dashboard');
	    
	    Route::get('change-password', 'ChangePasswordController@index')
			->name('password.change');
		Route::post('change-password', 'ChangePasswordController@store')
			->name('password.update');
	    
		//Resource routes
		Route::resource('/users', 'UserController');
		Route::resource('/packages', 'PackageController');
		Route::resource('/tasks', 'TaskController');
		Route::resource('/quote-videos', 'QuoteVideoController');
		Route::resource('/user-profiles', 'UserProfileController');
		Route::resource('/user-tasks', 'UserTaskController');
		Route::resource('/appointments', 'AppointmentController');
		Route::resource('/user-forms', 'UsersFromController');
	});

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Kyslik\ColumnSortable\Sortable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Task extends Model
{
    use Notifiable, Sortable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'user_id'
    ];

    /**
     * The accessors attributes that should be available in json.
     *
     * @var array
     */
    protected $appends = ['hash_id'];

    public function getHashIdAttribute() {
        $hashids = new \Hashids\Hashids(config('app.key'));
        return $hashids->encode($this->id);
    }

    public function user() {
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/Admin/TaskController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use \App\Task;
use Illuminate\Support\Facades\Auth;

class TaskController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $tasks = Task::withTrashed()
            ->sortable()
            ->paginate(15);
        } catch (\Kyslik\ColumnSortable\Exceptions\ColumnSortableException $e) {
        }
        
        $users = \App\User::where(['role_id' => config('custom.roles.student')])->get();
        return view('admin.task.index', [
            'tasks' => $tasks,
            'users' => $users
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //creating package
        $data=$request->input();
        $data['user_id'] = Auth::user()->id;
        $package = Task::create($data);
        return redirect(route('admin.tasks.index'))
            ->with('success', 'Task has been created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Task $task)
    {
        $data=$request->input();
        $task->fill($data);
        $task->save();
        return redirect()->route('admin.tasks.index')
            ->with('success', "Task has been updated successfully.");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::withTrashed()->find($id);
        $message='deleted';
        if ($task->trashed()) {
            $task->restore();
            $message='restored';
        } else {
            $task->delete();
        }

        return back()
            ->with('success', "Task has been $message successfully.");
    }
}

resources/views/admin/task/index.blade.php
@extends('layouts.admin')

@section('content')
  	<section>
        <div class="container-fluid">
          	<!-- Page Header-->
          	<header> 
          		<div class="row">
          			<div class="col-6">
            			<h2>Tasks</h2>
          			</div>
          			<div class="col-6 text-right">
          				<a href="javascript:void(0)" class="btn btn-default" data-toggle="modal" data-target="#assignTaskModal">
						    Assign Task
					  	</a>
          				<a href="javascript:void(0)" class="btn btn-primary" data-toggle="modal" data-target="#addTaskModal">
						    Add Task
					  	</a>
          			</div>
          		</div>
          		<!-- alert message component -->
            	<x-alert/>			
          	</header>
          	<div class="row">
            	<div class="col">
              		<div class="card">
		                <div class="card-body">
		                  	<div class="table-responsive">
		                    	<table class="table">
			                      	<thead>
				                        <tr>
				                          	<th>#</th>
				                          	<th>
				                          		@sortablelink('name', __(' Name'), ['page' => $tasks->currentPage()])
				                          	</th>
				                          	<th>
			                          			@sortablelink('created_at', __('Created at'))
				                          	</th>
				                          	<th>Created By</th>
				                          	<th>
				                          		{{ __('Action') }}
				                          	</th>
				                        </tr>
			                      	</thead>
			                      	<tbody>
			                      		@if (count($tasks))
										    @foreach ($tasks as $task)
						                        <tr>
						                          	<th scope="row">{{$loop->index+1}}</th>
						                          	<td>{{ $task->name }}</td>
						                          	<td>
						                          		{{ $task->created_at->isoFormat(env('DATE_FORMAT')) }}
						                          	</td>
						                          	<td>
						                          		{{ ucwords($task->user->name) }}
						                          	</td>
						                          	<td>
					                          			<i class="fa fa-edit" data-obj="<?= base64_encode(json_encode($task)) ?>" data-url="{{ route('admin.tasks.update', ['task' => $task->hash_id]) }}"></i>
						                          		@if(!$task->deleted_at)
						                          			<i class="fa fa-trash" data-url="{{ route('admin.tasks.destroy', ['task' => $task->hash_id]) }}" data-message= 'Delete'>
						                          		@else
						                          			<i class="fa fa-undo" data-url="{{ route('admin.tasks.destroy', ['task' => $task->hash_id]) }}" data-message= 'Restore'>
						                          		@endif
						                          		</i>
						                          	</td>
						                        </tr>
										    @endforeach
										@else
										    <tr> <td colspan=4> {{__('No Record Found.') }}</td></tr>
										@endif
			                      		
			                      	</tbody>
			                    </table>
			                    <div class="text-right">
			                    	{!! $tasks->appends(\Request::except('page'))->render() !!}
			                    </div>
		                  	</div>
		                </div>
	              	</div>
	            </div>
          	</div>
        </div>
  	</section>
  	<form method="POST" action="" id="DeletePackageForm">
  		@method('DELETE')
        @csrf
  		
  	</form>
@endsection

@section('modal')
    @include('modals.admin.task.add')
    @include('modals.admin.task.edit')
    @include('modals.admin.task.assign')
@endsection

@push('css')
	<link rel="stylesheet" href="{{ asset('css/common/jquery-ui.css') }}"></link>
@endpush

@push('scripts')
    <script src="{{ asset('js/common/jquery-validation/jquery.validate.min.js') }}"></script>
    <script type="text/javascript" src="{{asset('js/common/jquery-ui.js')}}"></script>
	<script type="text/javascript" src="{{ asset('js/admin/task/add.js') }}"></script>
@endpush