routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/sign-In', function () {
	return view('pages.signIn');
});

Route::get('/signup', function () {
	return view('pages.signup');
});

Route::get('/dashboard', function () {
	return view('pages.dashboard');
})->name('dashboard')->middleware('auth')->middleware('verified');

Route::get('/tasks', function () {
	return view('pages.tasks');
});

Route::get('/appointments', function () {
	return view('pages.appointments');
});

Route::get('/appointmentNotes', function () {
	return view('pages.appointmentNotes');
});

Route::get('/myProfile', function () {
	return view('pages.myProfile');
});

Route::get('/uploads', function () {
	return view('pages.uploads');
});

Route::get('/packages', function () {
	return view('pages.packages');
});

Route::get('/paymentSuccessful', function () {
	return view('pages.paymentSuccessful');
});

Route::get('/sessionVideo', function () {
	return view('pages.recordedSessionVideo');
});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');
Route::post('change-password', 'ChangePasswordController@save')->name('change-password');

Route::resource('/users', 'UserController');
// Route::resource('/tasks', 'TaskController');
// Route::resource('/packages', 'PackageController');
// Route::resource('/appointments', 'AppointmentsController');

// Controllers Within The "App\Http\Controllers\Admin" Namespace
Route::namespace('Admin')
	->prefix('admin')
	->name('admin.')
	->group(function () {
		Route::get('/', function () {
	        return view('admin.login');
	    })
	    ->name('login')
	    ->middleware('guest');

		Route::get('/dashboard', function () {
	        return view('admin.dashboard');
	    })->name('dashboard');
	    
	    Route::get('change-password', 'ChangePasswordController@index')
			->name('password.change');
		Route::post('change-password', 'ChangePasswordController@store')
			->name('password.update');
	    
		//Resource routes
		Route::resource('/users', 'UserController');
		Route::resource('/packages', 'PackageController');
		Route::resource('/tasks', 'TaskController');
		Route::resource('/quote-videos', 'QuoteVideoController');
		Route::resource('/user-profiles', 'UserProfileController');
		Route::resource('/user-tasks', 'UserTaskController');
		Route::resource('/appointments', 'AppointmentController');
		Route::resource('/user-forms', 'UsersFromController');
	});

resources/views/admin/user_form/create.blade.php
@extends('layouts.admin')
@section('content')
	<section>
	    <div class="container-fluid">
	      	<!-- Page Header-->
	      	<header> 
	      		<div class="row">
	      			<div class="col-6">
	        			<h2>Assign Forms</h2>
	      			</div>
	      		</div>
          		<!-- alert message component -->
            	<x-alert/>					
	      	</header>
	      	<div class="row">
	        	<div class="col-md-7 mx-auto">
	          		<div class="card">
		                <div class="card-body">
		                  	<form method="POST" action="{{ route('admin.user-forms.store') }}" id="PackageForm">
	                            @csrf
	                            <div class="form-group">
	                                <label for="FormName">{{ __('Select Form') }}</label>
	                                <select name="form_id" class="form-control" id="FormName" value="{{ old('form_id') }}" required>
	                                	@foreach($forms as $form)
		                                	<option value="{{$form->id}}">
		                                		{{$form->title}}
		                                	</option> 
	                                	@endforeach
	                                </select>
	                                @error('name')
	                                    <label class="">{{ $message }}</label>
	                                @enderror
	                            </div>
	                            <div class="form-group">
	                                <label for="UserName">{{ __('Select client which you want to send the form') }}</label>
	                                <select name="user_id" class="form-control" id="UserName" rows="2" required >
	                                	@foreach($users as $user)
		                                	<option value="{{$user->id}}">
		                                		{{$user->full_name}}
		                                	</option> 
	                                	@endforeach
	                                </select>
	                                @error('user_id')
	                                    <label class="">{{ $message }}</label>
	                                @enderror
	                            </div>

	                            <div class="form-group text-right">
	                            	<a href="{{route('admin.packages.index')}}" class="btn btn-default">Cancel</a>
	                            	<button type="submit" class="btn btn-success">Submit</button>
	                            </div>
	                        </form>
		                </div>
	              	</div>
	            </div>
	      	</div>
	    </div>
	</section>
@endsection
@push('css')
	<link rel="stylesheet" href="{{ asset('css/common/jquery-ui.css') }}"></link>
	<link rel="stylesheet" href="{{ asset('css/common/jquery.timepicker.min.css') }}"></link>
@endpush
@push('scripts')
    <script type="text/javascript" src="{{asset('js/common/jquery-ui.js')}}"></script>
    <script src="{{ asset('js/common/jquery-validation/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('js/common/jquery.timepicker.min.js') }}"></script>
	<script type="text/javascript" src="{{ asset('js/admin/package/create.js') }}"></script>
@endpush